modules:
  - type: script
    scripts:
      - "system/system-apps/install-dive-rpm.sh"
  - type: rpm-ostree
    install:
      - ydotool
  - type: files
    files:
      - "system/system-apps/distrobox": /