workspace=1, persisent:true, default:true, monitor:0
workspace=2, persisent:true, monitor:0
workspace=3, persisent:true, monitor:1
workspace=4, persisent:true, monitor:1

workspace=special:space, persisent:true
workspace=special:terminal, persistent:true, on-created-empty:$terminal
workspace=special:cross, persistent:true
