modules:
  # bureau de base
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/leloubil/brillo/repo/fedora-%OS_VERSION%/leloubil-brillo-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
    install:
      - hyprland
      - kitty
      - waybar
      - dunst
      - wofi
      - pipewire
      - wireplumber
      - network-manager-applet
      - brillo
      - swww
      - eww-wayland-git
      - pyprland
      - hyprland-contrib
      - hyprland-plugins
      - hyprlock
      - hypridle
      - hyprpicker
  - type: files
    files:
      - "desktop/config": /
  - type: files
    files:
      - "desktop/fonts": /
  - type: files
    files:
      - "desktop/sessions": /
  - type: files
    files:
      - "desktop/sddm": /
  # util
  - type: rpm-ostree
    install:
      - copyq
      # - hyprpicker
  # compatibilité
  - type: rpm-ostree
    install:
      - xdg-desktop-portal-hyprland
      - polkit-kde
      - qt6-qtwayland
      - qt5-qtwayland
