theme {
  color_scheme = "/usr/share/desktop-config/hypr/Black.colors"
  icon_theme = "Breeze"
  style = "kvantum-dark"

  font_fixed = "VCR OSD Mono"
  font_fixed_size = 12
  font = "VCR OSD Mono"
  font_size = 12
}


misc {
  single_click_activate = true
  menus_have_icons = true
  shortcuts_for_context_menus = true
}
